# Generated by Django 4.1.4 on 2023-07-03 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_image_purchased_by_alter_image_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 14, 56, 18, 525858)),
        ),
    ]
